apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudbeat
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
spec:
  template:
    spec:
      containers:
        - name: cloudbeat
          env:
            - name: ES_PASSWORD
              $patch: delete
