// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery v2.15.0. DO NOT EDIT.

package iam

import mock "github.com/stretchr/testify/mock"

// MockFactoryOption is an autogenerated mock type for the FactoryOption type
type MockFactoryOption struct {
	mock.Mock
}

type MockFactoryOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactoryOption) EXPECT() *MockFactoryOption_Expecter {
	return &MockFactoryOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: e
func (_m *MockFactoryOption) Execute(e *IAMFactory) {
	_m.Called(e)
}

// MockFactoryOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFactoryOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - e *IAMFactory
func (_e *MockFactoryOption_Expecter) Execute(e interface{}) *MockFactoryOption_Execute_Call {
	return &MockFactoryOption_Execute_Call{Call: _e.mock.On("Execute", e)}
}

func (_c *MockFactoryOption_Execute_Call) Run(run func(e *IAMFactory)) *MockFactoryOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*IAMFactory))
	})
	return _c
}

func (_c *MockFactoryOption_Execute_Call) Return() *MockFactoryOption_Execute_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewMockFactoryOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFactoryOption creates a new instance of MockFactoryOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFactoryOption(t mockConstructorTestingTNewMockFactoryOption) *MockFactoryOption {
	mock := &MockFactoryOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
